### ISSUE TITLE
there are some problems in making 

### ISSUE THREAD

**Issue by dianjituodong** [limbo018/OpenMPL#6]
when "[ 100%] Linking CXX executable OpenMPL",it shows "在SimpleMPL.cpp:中，对boost::timer::format...未定义的引用"
the version of the boost and the  gcc that I had was not suitable，so I choose the version that the author  recommends，it works

**Comment by Vincent-Ricardo** [comment]
Hi, which version of the boost and the gcc is that the author recommends

> when "[ 100%] Linking CXX executable OpenMPL",it shows "在SimpleMPL.cpp:中，对boost::timer::format...未定义的引用"
> the version of the boost and the gcc that I had was not suitable，so I choose the version that the author recommends，it works

**Comment by wadmes** [comment]
We released the docker version of OpenMPL recently, please refer to the cell_library branch for more information
